# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af57edeb0fadea08c1aa53406ca65dc99c11c726663f7f9510ba9fce56dd49024ab76e9d36e90f93b64acf0ef931a8c0c1538caa1a2c9a3acf2696bfc62a3a36

test:
  secret_key_base: ba1eae679fdae6b35a3fcb33c3a4d2f31b4f0342f4cfa69ae1d62090fff1f8ede31ea9baf17ff98939ec9ca21833fd20ff8cc61dde5eacc32ac6f204bae0920b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
